
export const GET_REPO_LOADING = 'GET_REPO_LOADING';
export const GET_REPO_SUCCESS = 'GET_REPO_SUCCESS';
export const GET_REPO_ERROR = 'GET_REPO_ERROR';

export const GET_SINGLE_REPO_LOADING = 'GET_SINGLE_REPO_LOADING'
export const GET_SINGLE_REPO_SUCCESS = 'GET_SINGLE_REPO_SUCCESS'
export const GET_SINGLE_REPO_ERROR = 'GET_SINGLE_REPO_ERROR'



export interface e {
  key: string
}

